apiVersion: batch/v1
kind: CronJob
metadata:
  name: etl-cron
  namespace: analytics-data
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: etl
              image: ghcr.io/pepalegre/docker-k8s-101/etl:latest
              env:
                - name: DATABASE_URL
                  value: postgresql://analytics:analytics@db:5432/analytics